//Node.js provided a way to run JavaScript code from outside a browser
//it freed JS from the browswer's confines and led directly to JS's current popularity
//now can use JS to write applications, incluidng browser, server, mobile, and desktop apps
//Abstraction ensures users are far removed from what's happening under the hood
//JS getinterpretedin the runtime environment bu an engine written in some other still-lower-level language 
//like C++, in turn these engines convert JS code into other even lower-level code until, after several
//iterations, the original code ends up a series of 1s and 0s
//higher level abstraction; jQuery & React libraries that let JS devs build programs on top of existing 
//components
//a runtime environment is the execution enviro provided to an application program by the operating system
//it lets the application access ssytem resources and provides tools the app needs to operate
//the runtime environment turns an application from a set of instructions into something that performs
//actual work
//API
//Application Programming Interface allows an application access an operating system's resources
//Runtime environent adds another layer of abstraction on top of the operating system's API to make these resources 
//available with a higher level API.  Runtime makes the API compatible with the operating system's API?
//The compiler and the operating system's API together make up a runtime environment
//they provide the tools an application needs to run
//Types of runtime environments:
//Browser - almost every browser has a JavaScript engine built into it
//2 purposes in the browser:
//1) alter web pages 
//2) exchange messages with a server over a network
// first #1, programmer needs an API to manipulate the structure and appearance of the HTML page  
console.log("Hello world")
